CREATE TABLE ${SCHEMA_NAME}.projects (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    workspace_id UUID NOT NULL,
    extension_install_id UUID NOT NULL,
    team_id UUID,
    name TEXT NOT NULL,
    slug TEXT NOT NULL DEFAULT '',
    repository TEXT NOT NULL DEFAULT '',
    platform TEXT NOT NULL DEFAULT '',
    environment TEXT NOT NULL DEFAULT '',
    dsn TEXT NOT NULL DEFAULT '',
    public_key TEXT NOT NULL DEFAULT '',
    secret_key TEXT NOT NULL DEFAULT '',
    app_key TEXT NOT NULL DEFAULT '',
    project_number BIGINT NOT NULL DEFAULT 0,
    events_per_hour INTEGER NOT NULL DEFAULT 1000,
    storage_quota_mb INTEGER NOT NULL DEFAULT 500,
    retention_days INTEGER NOT NULL DEFAULT 90,
    status TEXT NOT NULL DEFAULT 'active',
    event_count BIGINT NOT NULL DEFAULT 0,
    last_event_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ${SCHEMA_NAME}.issues (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    workspace_id UUID NOT NULL,
    extension_install_id UUID NOT NULL,
    project_id UUID NOT NULL REFERENCES ${SCHEMA_NAME}.projects(id),
    title TEXT NOT NULL,
    culprit TEXT NOT NULL DEFAULT '',
    fingerprint TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'unresolved',
    level TEXT NOT NULL DEFAULT 'error',
    type TEXT NOT NULL DEFAULT '',
    first_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_count BIGINT NOT NULL DEFAULT 0,
    user_count BIGINT NOT NULL DEFAULT 0,
    assigned_to TEXT,
    resolved_at TIMESTAMPTZ,
    resolved_by TEXT,
    resolution TEXT NOT NULL DEFAULT '',
    resolution_notes TEXT NOT NULL DEFAULT '',
    resolved_in_commit TEXT NOT NULL DEFAULT '',
    resolved_in_version TEXT NOT NULL DEFAULT '',
    has_related_case BOOLEAN NOT NULL DEFAULT false,
    related_case_ids JSONB NOT NULL DEFAULT '[]',
    tags JSONB NOT NULL DEFAULT '{}',
    permalink TEXT NOT NULL DEFAULT '',
    short_id TEXT NOT NULL DEFAULT '',
    logger TEXT NOT NULL DEFAULT '',
    platform TEXT NOT NULL DEFAULT '',
    last_event_id TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ${SCHEMA_NAME}.error_events (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    workspace_id UUID NOT NULL,
    extension_install_id UUID NOT NULL,
    event_id TEXT NOT NULL,
    project_id UUID NOT NULL REFERENCES ${SCHEMA_NAME}.projects(id),
    issue_id UUID REFERENCES ${SCHEMA_NAME}.issues(id),
    timestamp TIMESTAMPTZ NOT NULL,
    received TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    message TEXT NOT NULL DEFAULT '',
    level TEXT NOT NULL DEFAULT 'error',
    logger TEXT NOT NULL DEFAULT '',
    platform TEXT NOT NULL DEFAULT '',
    environment TEXT NOT NULL DEFAULT '',
    release TEXT NOT NULL DEFAULT '',
    dist TEXT NOT NULL DEFAULT '',
    exception JSONB NOT NULL DEFAULT '[]',
    stacktrace JSONB NOT NULL DEFAULT '{}',
    "user" JSONB NOT NULL DEFAULT '{}',
    request JSONB NOT NULL DEFAULT '{}',
    tags JSONB NOT NULL DEFAULT '{}',
    extra JSONB NOT NULL DEFAULT '{}',
    contexts JSONB NOT NULL DEFAULT '{}',
    breadcrumbs JSONB NOT NULL DEFAULT '[]',
    fingerprint JSONB NOT NULL DEFAULT '[]',
    data_url TEXT NOT NULL DEFAULT '',
    size BIGINT NOT NULL DEFAULT 0,
    processed_at TIMESTAMPTZ,
    grouped_at TIMESTAMPTZ
);

CREATE TABLE ${SCHEMA_NAME}.alerts (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    workspace_id UUID NOT NULL,
    extension_install_id UUID NOT NULL,
    project_id UUID NOT NULL REFERENCES ${SCHEMA_NAME}.projects(id),
    name TEXT NOT NULL,
    conditions JSONB NOT NULL DEFAULT '[]',
    frequency BIGINT NOT NULL DEFAULT 0,
    actions JSONB NOT NULL DEFAULT '[]',
    enabled BOOLEAN NOT NULL DEFAULT true,
    cooldown_minutes INTEGER NOT NULL DEFAULT 60,
    last_triggered TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
