package servicedomain

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/movebigrocks/platform/pkg/id"
)

// AttachmentStatus represents the status of an attachment
type AttachmentStatus string

const (
	AttachmentStatusPending  AttachmentStatus = "pending"  // Uploaded, awaiting scan
	AttachmentStatusScanning AttachmentStatus = "scanning" // Being scanned
	AttachmentStatusClean    AttachmentStatus = "clean"    // Passed virus scan
	AttachmentStatusInfected AttachmentStatus = "infected" // Failed virus scan
	AttachmentStatusError    AttachmentStatus = "error"    // Scan failed
)

// AttachmentSource represents where the attachment came from
type AttachmentSource string

const (
	AttachmentSourceEmail  AttachmentSource = "email"  // From inbound email
	AttachmentSourceUpload AttachmentSource = "upload" // Direct upload via API
	AttachmentSourceAgent  AttachmentSource = "agent"  // Attached by support agent
	AttachmentSourceSystem AttachmentSource = "system" // Generated by system
)

// Attachment represents a file attachment stored in S3
type Attachment struct {
	ID          string
	WorkspaceID string

	// File information
	Filename    string
	ContentType string
	Size        int64 // bytes

	// Storage location
	S3Bucket   string
	S3Key      string
	StorageKey string // Legacy: filesystem storage path

	// Security
	Status     AttachmentStatus
	ScanResult string // ClamAV result string
	ScannedAt  *time.Time
	SHA256Hash string // For deduplication/verification

	// Context
	Source     AttachmentSource
	CaseID     string
	EmailID    string // Inbound or outbound email ID
	ContactID  string
	UploadedBy string // User ID if uploaded by agent

	// Metadata
	Description string
	Metadata    map[string]string

	// Timestamps
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

// NewAttachment creates a new attachment record
func NewAttachment(workspaceID, filename, contentType string, size int64, source AttachmentSource) *Attachment {
	return &Attachment{
		ID:          id.New(),
		WorkspaceID: workspaceID,
		Filename:    sanitizeFilename(filename),
		ContentType: contentType,
		Size:        size,
		Status:      AttachmentStatusPending,
		Source:      source,
		Metadata:    make(map[string]string),
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}
}

// SetS3Location sets the S3 storage location
func (a *Attachment) SetS3Location(bucket, key string) {
	a.S3Bucket = bucket
	a.S3Key = key
	a.UpdatedAt = time.Now()
}

// MarkScanning marks the attachment as being scanned
func (a *Attachment) MarkScanning() {
	a.Status = AttachmentStatusScanning
	a.UpdatedAt = time.Now()
}

// MarkClean marks the attachment as passing virus scan
func (a *Attachment) MarkClean(scanResult string) {
	now := time.Now()
	a.Status = AttachmentStatusClean
	a.ScanResult = scanResult
	a.ScannedAt = &now
	a.UpdatedAt = now
}

// MarkInfected marks the attachment as failing virus scan
func (a *Attachment) MarkInfected(scanResult string) {
	now := time.Now()
	a.Status = AttachmentStatusInfected
	a.ScanResult = scanResult
	a.ScannedAt = &now
	a.UpdatedAt = now
}

// MarkError marks the attachment as having a scan error
func (a *Attachment) MarkError(errorMsg string) {
	now := time.Now()
	a.Status = AttachmentStatusError
	a.ScanResult = errorMsg
	a.ScannedAt = &now
	a.UpdatedAt = now
}

func AttachmentStatusFromScan(isScanned bool, scanResult string) AttachmentStatus {
	if !isScanned {
		return AttachmentStatusPending
	}

	normalized := strings.ToLower(strings.TrimSpace(scanResult))

	switch {
	case normalized == "clean", strings.Contains(normalized, "no threats detected"):
		return AttachmentStatusClean
	case normalized == "infected", strings.Contains(normalized, "threat detected"), strings.Contains(normalized, "malware"), strings.Contains(normalized, "virus"):
		return AttachmentStatusInfected
	default:
		return AttachmentStatusError
	}
}

// IsClean returns true if the attachment passed virus scanning
func (a *Attachment) IsClean() bool {
	return a.Status == AttachmentStatusClean
}

// IsQuarantined returns true if the attachment should be quarantined
func (a *Attachment) IsQuarantined() bool {
	return a.Status == AttachmentStatusInfected
}

// GetS3Path returns the full S3 path for this attachment
func (a *Attachment) GetS3Path() string {
	return fmt.Sprintf("s3://%s/%s", a.S3Bucket, a.S3Key)
}

// GenerateS3Key generates an S3 key for this attachment
func (a *Attachment) GenerateS3Key() string {
	// Format: {workspace_id}/attachments/{year}/{month}/{attachment_id}/{filename}
	now := time.Now()
	storageID := a.ID
	if storageID == "" {
		storageID = id.New()
	}
	return fmt.Sprintf("%s/attachments/%d/%02d/%s/%s",
		a.WorkspaceID,
		now.Year(),
		now.Month(),
		storageID,
		a.Filename,
	)
}

// Validate validates attachment business rules
func (a *Attachment) Validate() error {
	if a.WorkspaceID == "" {
		return fmt.Errorf("workspace_id is required")
	}
	if a.Filename == "" {
		return fmt.Errorf("filename is required")
	}
	if a.Size <= 0 {
		return fmt.Errorf("size must be positive")
	}
	if a.Size > MaxAttachmentSize {
		return fmt.Errorf("attachment size %d exceeds maximum %d bytes", a.Size, MaxAttachmentSize)
	}
	if !isAllowedContentType(a.ContentType) {
		return fmt.Errorf("content type %s is not allowed", a.ContentType)
	}
	return nil
}

// MaxAttachmentSize is the maximum allowed attachment size (25MB)
const MaxAttachmentSize = 25 * 1024 * 1024

// AllowedContentTypes lists allowed attachment MIME types
var AllowedContentTypes = map[string]bool{
	// Documents
	"application/pdf":    true,
	"application/msword": true,
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document": true,
	"application/vnd.ms-excel": true,
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":         true,
	"application/vnd.ms-powerpoint":                                             true,
	"application/vnd.openxmlformats-officedocument.presentationml.presentation": true,
	"text/plain":       true,
	"text/csv":         true,
	"text/html":        true,
	"application/json": true,
	"application/xml":  true,

	// Images
	"image/jpeg":    true,
	"image/png":     true,
	"image/gif":     true,
	"image/webp":    true,
	"image/svg+xml": true,
	"image/bmp":     true,

	// Archives (scanned before extraction)
	"application/zip":              true,
	"application/x-zip-compressed": true,
	"application/gzip":             true,
	"application/x-tar":            true,

	// Other common types
	"application/octet-stream": true, // Generic binary - will rely on virus scan
}

// BlockedExtensions lists file extensions that are always blocked
var BlockedExtensions = map[string]bool{
	".exe": true, ".dll": true, ".bat": true, ".cmd": true,
	".com": true, ".msi": true, ".scr": true, ".pif": true,
	".vbs": true, ".js": true, ".jse": true, ".wsf": true,
	".wsh": true, ".ps1": true, ".psm1": true, ".psd1": true,
}

// isAllowedContentType checks if a content type is allowed
func isAllowedContentType(contentType string) bool {
	// Normalize content type (remove parameters like charset)
	if idx := strings.Index(contentType, ";"); idx != -1 {
		contentType = strings.TrimSpace(contentType[:idx])
	}
	return AllowedContentTypes[strings.ToLower(contentType)]
}

// sanitizeFilename removes dangerous characters from filename
func sanitizeFilename(filename string) string {
	// Get just the base filename (no path)
	filename = filepath.Base(filename)

	// Remove null bytes and path separators
	filename = strings.ReplaceAll(filename, "\x00", "")
	filename = strings.ReplaceAll(filename, "/", "_")
	filename = strings.ReplaceAll(filename, "\\", "_")

	// Limit length
	if len(filename) > 255 {
		ext := filepath.Ext(filename)
		filename = filename[:255-len(ext)] + ext
	}

	return filename
}

// IsBlockedExtension checks if a filename has a blocked extension
func IsBlockedExtension(filename string) bool {
	ext := strings.ToLower(filepath.Ext(filename))
	return BlockedExtensions[ext]
}
