-- =============================================================================
-- Disable core row-level security enforcement (rollback)
-- =============================================================================
-- Reverses deploy/rls/enable-core-rls.sql: drops the tenant_isolation policy and
-- disables (and unforces) row-level security on every tenant-scoped core table,
-- returning tenant isolation to the application layer alone. Idempotent; needs
-- no redeploy. The workspace-context function is left in place because it is
-- harmless when no policy references it.
-- =============================================================================

DROP POLICY IF EXISTS tenant_isolation ON core_automation.assignment_rules;
ALTER TABLE core_automation.assignment_rules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.assignment_rules DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.job_executions;
ALTER TABLE core_automation.job_executions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.job_executions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.job_queues;
ALTER TABLE core_automation.job_queues NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.job_queues DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.job_templates;
ALTER TABLE core_automation.job_templates NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.job_templates DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.jobs;
ALTER TABLE core_automation.jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.jobs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.recurring_jobs;
ALTER TABLE core_automation.recurring_jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.recurring_jobs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.rule_executions;
ALTER TABLE core_automation.rule_executions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.rule_executions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.rules;
ALTER TABLE core_automation.rules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.rules DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.workflow_instances;
ALTER TABLE core_automation.workflow_instances NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.workflow_instances DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_automation.workflows;
ALTER TABLE core_automation.workflows NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_automation.workflows DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_governance.alert_rules;
ALTER TABLE core_governance.alert_rules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_governance.alert_rules DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_governance.audit_configurations;
ALTER TABLE core_governance.audit_configurations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_governance.audit_configurations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_governance.audit_log_retentions;
ALTER TABLE core_governance.audit_log_retentions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_governance.audit_log_retentions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_governance.audit_logs;
ALTER TABLE core_governance.audit_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_governance.audit_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_governance.custom_fields;
ALTER TABLE core_governance.custom_fields NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_governance.custom_fields DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_governance.security_events;
ALTER TABLE core_governance.security_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_governance.security_events DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.agent_tokens;
ALTER TABLE core_identity.agent_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.agent_tokens DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.agents;
ALTER TABLE core_identity.agents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.agents DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.notifications;
ALTER TABLE core_identity.notifications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.notifications DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.portal_access_tokens;
ALTER TABLE core_identity.portal_access_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.portal_access_tokens DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.roles;
ALTER TABLE core_identity.roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.roles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.subscriptions;
ALTER TABLE core_identity.subscriptions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.subscriptions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.user_roles;
ALTER TABLE core_identity.user_roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.user_roles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.user_workspace_roles;
ALTER TABLE core_identity.user_workspace_roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.user_workspace_roles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_identity.workspace_memberships;
ALTER TABLE core_identity.workspace_memberships NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_identity.workspace_memberships DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_knowledge.case_knowledge_resource_links;
ALTER TABLE core_knowledge.case_knowledge_resource_links NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_knowledge.case_knowledge_resource_links DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_knowledge.knowledge_resources;
ALTER TABLE core_knowledge.knowledge_resources NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_knowledge.knowledge_resources DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_platform.contacts;
ALTER TABLE core_platform.contacts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_platform.contacts DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_platform.team_members;
ALTER TABLE core_platform.team_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_platform.team_members DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_platform.teams;
ALTER TABLE core_platform.teams NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_platform.teams DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_platform.workspace_settings;
ALTER TABLE core_platform.workspace_settings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_platform.workspace_settings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.attachments;
ALTER TABLE core_service.attachments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.attachments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.case_assignment_history;
ALTER TABLE core_service.case_assignment_history NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.case_assignment_history DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.case_queues;
ALTER TABLE core_service.case_queues NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.case_queues DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.cases;
ALTER TABLE core_service.cases NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.cases DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.communications;
ALTER TABLE core_service.communications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.communications DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.conversation_messages;
ALTER TABLE core_service.conversation_messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.conversation_messages DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.conversation_outcomes;
ALTER TABLE core_service.conversation_outcomes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.conversation_outcomes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.conversation_participants;
ALTER TABLE core_service.conversation_participants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.conversation_participants DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.conversation_sessions;
ALTER TABLE core_service.conversation_sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.conversation_sessions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.conversation_working_state;
ALTER TABLE core_service.conversation_working_state NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.conversation_working_state DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.email_blacklists;
ALTER TABLE core_service.email_blacklists NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.email_blacklists DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.email_stats;
ALTER TABLE core_service.email_stats NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.email_stats DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.email_templates;
ALTER TABLE core_service.email_templates NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.email_templates DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.email_thread_links;
ALTER TABLE core_service.email_thread_links NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.email_thread_links DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.email_threads;
ALTER TABLE core_service.email_threads NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.email_threads DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.form_access_tokens;
ALTER TABLE core_service.form_access_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.form_access_tokens DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.form_specs;
ALTER TABLE core_service.form_specs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.form_specs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.form_submissions;
ALTER TABLE core_service.form_submissions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.form_submissions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.inbound_emails;
ALTER TABLE core_service.inbound_emails NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.inbound_emails DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.outbound_emails;
ALTER TABLE core_service.outbound_emails NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.outbound_emails DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.quarantined_messages;
ALTER TABLE core_service.quarantined_messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.quarantined_messages DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.queue_items;
ALTER TABLE core_service.queue_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.queue_items DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.service_catalog_bindings;
ALTER TABLE core_service.service_catalog_bindings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.service_catalog_bindings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.service_catalog_nodes;
ALTER TABLE core_service.service_catalog_nodes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.service_catalog_nodes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.thread_analytics;
ALTER TABLE core_service.thread_analytics NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.thread_analytics DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.thread_merges;
ALTER TABLE core_service.thread_merges NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.thread_merges DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON core_service.thread_splits;
ALTER TABLE core_service.thread_splits NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_service.thread_splits DISABLE ROW LEVEL SECURITY;
