package clispec

type AuthMode string

const (
	AuthModeNone            AuthMode = "none"
	AuthModeLocal           AuthMode = "local"
	AuthModeBearerOrSession AuthMode = "bearer_or_session"
	AuthModeSessionOnly     AuthMode = "session_only"
)

type OperationKind string

const (
	OperationLocal OperationKind = "local"
	OperationRead  OperationKind = "read"
	OperationWrite OperationKind = "write"
)

type IdempotencyMode string

const (
	IdempotencyNotApplicable IdempotencyMode = "not_applicable"
	IdempotencyLocalState    IdempotencyMode = "local_state"
	IdempotencyReadOnly      IdempotencyMode = "read_only"
	IdempotencyServerManaged IdempotencyMode = "server_managed"
)

type FlagSpec struct {
	Name     string `json:"name"`
	Required bool   `json:"required,omitempty"`
}

type PositionalSpec struct {
	Name     string `json:"name"`
	Required bool   `json:"required,omitempty"`
}

type CommandSpec struct {
	Section      string           `json:"section"`
	Path         []string         `json:"path"`
	Usage        string           `json:"usage"`
	Summary      string           `json:"summary"`
	SupportsJSON bool             `json:"supportsJson"`
	AuthMode     AuthMode         `json:"authMode"`
	AuthNote     string           `json:"authNote,omitempty"`
	Operation    OperationKind    `json:"operation"`
	Idempotency  IdempotencyMode  `json:"idempotency"`
	Positionals  []PositionalSpec `json:"positionals,omitempty"`
	Flags        []FlagSpec       `json:"flags,omitempty"`
	Notes        []string         `json:"notes,omitempty"`
}

type SectionSpec struct {
	Key   string   `json:"key"`
	Title string   `json:"title"`
	Notes []string `json:"notes,omitempty"`
}

type AuthModeSpec struct {
	Name        AuthMode `json:"name"`
	Label       string   `json:"label"`
	Description string   `json:"description"`
}

type Spec struct {
	SchemaVersion           string         `json:"schemaVersion"`
	PrimarySurface          string         `json:"primarySurface"`
	CanonicalMachineAPI     string         `json:"canonicalMachineApi"`
	CommandRegistrySource   string         `json:"commandRegistrySource"`
	ExtensionInstallSources []string       `json:"extensionInstallSources"`
	AuthModes               []AuthModeSpec `json:"authModes"`
	Sections                []SectionSpec  `json:"sections"`
	Commands                []CommandSpec  `json:"commands"`
}

var sections = []SectionSpec{
	{Key: "auth", Title: "auth", Notes: []string{"If no token is supplied, `mbr auth login` opens the browser and stores a session-backed CLI login."}},
	{Key: "context", Title: "context", Notes: []string{"`mbr context set` stores the current workspace and team so agents can operate with much shorter commands."}},
	{Key: "spec", Title: "spec"},
	{Key: "workspaces", Title: "workspaces", Notes: []string{"`mbr workspaces create` requires browser login or `MBR_SESSION_TOKEN`."}},
	{Key: "teams", Title: "teams", Notes: []string{"Team creation and membership changes require browser login or `MBR_SESSION_TOKEN`. `--workspace` and `--team` default from stored CLI context when available."}},
	{Key: "agents", Title: "agents", Notes: []string{"Agent lifecycle, token creation, and membership changes require browser login or `MBR_SESSION_TOKEN`. Complex membership grants support `--input-file` or `--input-json` so agents can apply a complete policy payload in one shot."}},
	{Key: "catalog", Title: "catalog", Notes: []string{"`--workspace` defaults from stored CLI context when available."}},
	{Key: "forms", Title: "forms", Notes: []string{"`--workspace` defaults from stored CLI context when available."}},
	{Key: "knowledge", Title: "knowledge", Notes: []string{"`--workspace` and `--team` default from stored CLI context when available."}},
	{Key: "concepts", Title: "concepts", Notes: []string{"`--workspace` defaults from stored CLI context when available. Without a workspace, `mbr concepts list` returns only built-in concept specs."}},
	{Key: "artifacts", Title: "artifacts", Notes: []string{"Managed artifact commands target Git-backed extension surfaces such as published websites and templates."}},
	{Key: "queues", Title: "queues", Notes: []string{"`--workspace` defaults from stored CLI context when available."}},
	{Key: "conversations", Title: "conversations", Notes: []string{"`--workspace` defaults from stored CLI context when available."}},
	{Key: "forms", Title: "forms", Notes: []string{"Forms commands require browser login or `MBR_SESSION_TOKEN`. `--workspace` defaults from stored CLI context when available."}},
	{Key: "automation", Title: "automation", Notes: []string{"Automation rule commands require browser login or `MBR_SESSION_TOKEN`. `--workspace` defaults from stored CLI context when available."}},
	{Key: "cases", Title: "cases", Notes: []string{"`--workspace` defaults from stored CLI context when available."}},
	{Key: "contacts", Title: "contacts", Notes: []string{"`--workspace` defaults from stored CLI context when available."}},
	{Key: "attachments", Title: "attachments", Notes: []string{"`--workspace` defaults from stored CLI context when available."}},
	{Key: "health", Title: "health"},
	{Key: "fleet", Title: "fleet", Notes: []string{"`mbr fleet register` explicitly registers one deployed instance with the Move Big Rocks fleet control plane and can persist a newly issued tracking secret to a local file. The weekly heartbeat remains host-owned and optional from the instance template side."}},
	{Key: "extensions", Title: "extensions", Notes: []string{"`mbr extensions lint` validates a source tree offline against `extension.contract.json` and can refresh that file with `--write-contract`. `mbr extensions verify` installs from source and proves the resolved navigation, widgets, seeded resources, validation, and health surfaces. `mbr extensions install` accepts an optional `--license-token` for instance-bound or marketplace-managed bundle flows. Public first-party OCI bundles can install without it. Provisioning a dedicated workspace during install requires browser login or `MBR_SESSION_TOKEN`. Deactivate an extension before uninstalling it. Workspace-scoped extension commands default to stored CLI context when available."}},
	{Key: "extensions-skills", Title: "extensions skills"},
	{Key: "extensions-events", Title: "extensions events", Notes: []string{"`--workspace` defaults from stored CLI context when available."}},
}

var commands = []CommandSpec{
	{
		Section:      "auth",
		Path:         []string{"auth", "whoami"},
		Usage:        "mbr auth whoami [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show the current authenticated principal.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "auth",
		Path:         []string{"auth", "login"},
		Usage:        "mbr auth login --url URL [--token TOKEN | --token-stdin] [--json]",
		Summary:      "Bootstrap CLI credentials with a browser flow or token.",
		SupportsJSON: true,
		AuthMode:     AuthModeNone,
		AuthNote:     "Opens the browser when no token is supplied.",
		Operation:    OperationLocal,
		Idempotency:  IdempotencyLocalState,
		Flags: []FlagSpec{
			{Name: "--url", Required: true},
			{Name: "--token"},
			{Name: "--token-stdin"},
			{Name: "--json"},
		},
	},
	{
		Section:      "auth",
		Path:         []string{"auth", "logout"},
		Usage:        "mbr auth logout",
		Summary:      "Clear locally stored CLI credentials.",
		SupportsJSON: false,
		AuthMode:     AuthModeLocal,
		Operation:    OperationLocal,
		Idempotency:  IdempotencyLocalState,
	},
	{
		Section:      "context",
		Path:         []string{"context", "view"},
		Usage:        "mbr context view [--json]",
		Summary:      "Show the locally stored instance, workspace, and team context.",
		SupportsJSON: true,
		AuthMode:     AuthModeLocal,
		Operation:    OperationLocal,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--json"},
		},
	},
	{
		Section:      "context",
		Path:         []string{"context", "set"},
		Usage:        "mbr context set [--workspace WORKSPACE_ID] [--team TEAM_ID] [--clear-team | --clear] [--json]",
		Summary:      "Persist the current workspace and team for future CLI commands.",
		SupportsJSON: true,
		AuthMode:     AuthModeLocal,
		Operation:    OperationLocal,
		Idempotency:  IdempotencyLocalState,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--clear-team"},
			{Name: "--clear"},
			{Name: "--json"},
		},
	},
	{
		Section:      "spec",
		Path:         []string{"spec", "export"},
		Usage:        "mbr spec export [--json]",
		Summary:      "Export the machine-readable CLI contract.",
		SupportsJSON: true,
		AuthMode:     AuthModeNone,
		Operation:    OperationLocal,
		Idempotency:  IdempotencyNotApplicable,
		Flags:        []FlagSpec{{Name: "--json"}},
	},
	{
		Section:      "workspaces",
		Path:         []string{"workspaces", "list"},
		Usage:        "mbr workspaces list [--url URL] [--token TOKEN] [--json]",
		Summary:      "List visible workspaces.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "workspaces",
		Path:         []string{"workspaces", "create"},
		Usage:        "mbr workspaces create --name NAME --slug SLUG [--description TEXT] [--url URL] [--json]",
		Summary:      "Create a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--name", Required: true},
			{Name: "--slug", Required: true},
			{Name: "--description"},
			{Name: "--url"},
			{Name: "--json"},
		},
	},
	{
		Section:      "teams",
		Path:         []string{"teams", "list"},
		Usage:        "mbr teams list [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List teams in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "teams",
		Path:         []string{"teams", "create"},
		Usage:        "mbr teams create [--workspace WORKSPACE_ID] --name NAME [--description TEXT] [--email ADDRESS] [--response-hours N] [--resolution-hours N] [--auto-assign] [--auto-assign-keywords CSV] [--inactive] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a team.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--name", Required: true},
			{Name: "--description"},
			{Name: "--email"},
			{Name: "--response-hours"},
			{Name: "--resolution-hours"},
			{Name: "--auto-assign"},
			{Name: "--auto-assign-keywords"},
			{Name: "--inactive"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "teams",
		Path:         []string{"teams", "show"},
		Usage:        "mbr teams show TEAM_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a team.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "TEAM_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "teams",
		Path:         []string{"teams", "members", "list"},
		Usage:        "mbr teams members list [--team TEAM_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List members of a team.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--team"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "list"},
		Usage:        "mbr agents list [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List agents in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "show"},
		Usage:        "mbr agents show AGENT_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show an agent, including membership and tokens.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "create"},
		Usage:        "mbr agents create [--workspace WORKSPACE_ID] --name NAME [--description TEXT] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create an agent in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--name", Required: true},
			{Name: "--description"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "update"},
		Usage:        "mbr agents update AGENT_ID [--name NAME] [--description TEXT] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Update an agent.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--name"},
			{Name: "--description"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "suspend"},
		Usage:        "mbr agents suspend AGENT_ID --reason TEXT [--url URL] [--token TOKEN] [--json]",
		Summary:      "Suspend an agent.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--reason", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "activate"},
		Usage:        "mbr agents activate AGENT_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Activate a suspended agent.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "revoke"},
		Usage:        "mbr agents revoke AGENT_ID --reason TEXT [--url URL] [--token TOKEN] [--json]",
		Summary:      "Permanently revoke an agent.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--reason", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "tokens", "list"},
		Usage:        "mbr agents tokens list AGENT_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "List tokens for an agent.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "tokens", "create"},
		Usage:        "mbr agents tokens create AGENT_ID --name NAME [--expires-in-days N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a new token for an agent.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--name", Required: true},
			{Name: "--expires-in-days"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "tokens", "revoke"},
		Usage:        "mbr agents tokens revoke TOKEN_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Revoke an agent token.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "TOKEN_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "memberships", "show"},
		Usage:        "mbr agents memberships show AGENT_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show the workspace membership for an agent.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "memberships", "grant"},
		Usage:        "mbr agents memberships grant AGENT_ID [--workspace WORKSPACE_ID] [--role ROLE] [--permissions CSV] [--expires-in-days N] [--input-file PATH | --input-json JSON] [--allowed-ips CSV] [--allowed-projects CSV] [--allowed-teams CSV] [--allow-delegated-routing[=BOOL]] [--delegated-routing-teams CSV] [--active-hours-start HH:MM] [--active-hours-end HH:MM] [--active-timezone TZ] [--active-days CSV] [--rate-limit-per-minute N] [--rate-limit-per-hour N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Grant or update workspace membership for an agent with explicit policy constraints.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "AGENT_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--role"},
			{Name: "--permissions"},
			{Name: "--expires-in-days"},
			{Name: "--input-file"},
			{Name: "--input-json"},
			{Name: "--allowed-ips"},
			{Name: "--allowed-projects"},
			{Name: "--allowed-teams"},
			{Name: "--allow-delegated-routing"},
			{Name: "--delegated-routing-teams"},
			{Name: "--active-hours-start"},
			{Name: "--active-hours-end"},
			{Name: "--active-timezone"},
			{Name: "--active-days"},
			{Name: "--rate-limit-per-minute"},
			{Name: "--rate-limit-per-hour"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"Use `--input-file` or `--input-json` for a deliberate, versionable membership policy payload, then layer simple flag overrides on top when needed.",
		},
	},
	{
		Section:      "agents",
		Path:         []string{"agents", "memberships", "revoke"},
		Usage:        "mbr agents memberships revoke MEMBERSHIP_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Revoke an agent workspace membership.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "MEMBERSHIP_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "catalog",
		Path:         []string{"catalog", "list"},
		Usage:        "mbr catalog list [--workspace WORKSPACE_ID] [--parent NODE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List service catalog nodes for a workspace or parent node.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--parent"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "catalog",
		Path:         []string{"catalog", "show"},
		Usage:        "mbr catalog show NODE_ID_OR_PATH [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a service catalog node by ID or workspace path.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "node_id_or_path", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "specs", "list"},
		Usage:        "mbr forms specs list [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List form specs in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "specs", "show"},
		Usage:        "mbr forms specs show SPEC_ID_OR_SLUG [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a form spec by ID or workspace slug.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "spec_id_or_slug", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "specs", "create"},
		Usage:        "mbr forms specs create [--workspace WORKSPACE_ID] (--input-file PATH | --input-json JSON) [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a form spec from a structured JSON payload.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--input-file"},
			{Name: "--input-json"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"Complex form payloads are expected to come from a JSON file or inline JSON so agents can apply a complete spec in one shot.",
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "specs", "update"},
		Usage:        "mbr forms specs update SPEC_ID_OR_SLUG [--workspace WORKSPACE_ID] (--input-file PATH | --input-json JSON) [--url URL] [--token TOKEN] [--json]",
		Summary:      "Update a form spec from a structured JSON payload.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "spec_id_or_slug", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--input-file"},
			{Name: "--input-json"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "submissions", "list"},
		Usage:        "mbr forms submissions list [--workspace WORKSPACE_ID] [--spec SPEC_ID] [--status STATUS] [--limit N] [--offset N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List form submissions in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--spec"},
			{Name: "--status"},
			{Name: "--limit"},
			{Name: "--offset"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "submissions", "create"},
		Usage:        "mbr forms submissions create SPEC_ID_OR_SLUG [--workspace WORKSPACE_ID] (--input-file PATH | --input-json JSON) [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a form submission from a structured JSON payload.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "spec_id_or_slug", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--input-file"},
			{Name: "--input-json"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "submissions", "show"},
		Usage:        "mbr forms submissions show SUBMISSION_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a form submission by ID.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "submission_id", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "teams",
		Path:         []string{"teams", "members", "add"},
		Usage:        "mbr teams members add [--team TEAM_ID] --user USER_ID [--role ROLE] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Add a user to a team.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--team"},
			{Name: "--user", Required: true},
			{Name: "--role"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "list"},
		Usage:        "mbr knowledge list [--workspace WORKSPACE_ID] [--team TEAM_ID] [--surface SURFACE] [--review-status STATUS] [--kind KIND] [--status STATUS] [--search QUERY] [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List knowledge resources in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--review-status"},
			{Name: "--kind"},
			{Name: "--status"},
			{Name: "--search"},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "show"},
		Usage:        "mbr knowledge show RESOURCE [--workspace WORKSPACE_ID --team TEAM_ID --surface SURFACE] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a single knowledge resource by ID, or by slug when workspace, team, and surface are provided.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "RESOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "search"},
		Usage:        "mbr knowledge search QUERY [--workspace WORKSPACE_ID] [--team TEAM_ID] [--surface SURFACE] [--review-status STATUS] [--kind KIND] [--status STATUS] [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Search knowledge resources in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "QUERY", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--review-status"},
			{Name: "--kind"},
			{Name: "--status"},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "review-queue"},
		Usage:        "mbr knowledge review-queue [--workspace WORKSPACE_ID] [--team TEAM_ID] [--kind KIND] [--review-status STATUS] [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List knowledge items, such as RFCs, that need team review.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--kind"},
			{Name: "--review-status"},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "upsert"},
		Usage:        "mbr knowledge upsert [RESOURCE] [--workspace WORKSPACE_ID] [--team TEAM_ID] --slug SLUG [--surface SURFACE] [--title TITLE] [--kind KIND] [--concept-spec KEY] [--concept-version VERSION] [--status STATUS] [--summary TEXT] [--body TEXT | --file PATH] [--source-kind KIND] [--source-ref REF] [--path-ref PATH] [--channels CSV] [--share-with CSV] [--keywords CSV] [--frontmatter-file PATH | --frontmatter-json JSON] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a team-owned knowledge resource or update an existing one by ID or slug.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "RESOURCE"}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--slug", Required: true},
			{Name: "--surface"},
			{Name: "--title"},
			{Name: "--kind"},
			{Name: "--concept-spec"},
			{Name: "--concept-version"},
			{Name: "--status"},
			{Name: "--summary"},
			{Name: "--body"},
			{Name: "--file"},
			{Name: "--source-kind"},
			{Name: "--source-ref"},
			{Name: "--path-ref"},
			{Name: "--channels"},
			{Name: "--share-with"},
			{Name: "--keywords"},
			{Name: "--frontmatter-file"},
			{Name: "--frontmatter-json"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "checkout"},
		Usage:        "mbr knowledge checkout PATH [--workspace WORKSPACE_ID] [--team TEAM_ID] [--surface SURFACE] [--kind KIND] [--review-status STATUS] [--status STATUS] [--search QUERY] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Materialize an ACL-filtered local working copy of knowledge files.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "PATH", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--kind"},
			{Name: "--review-status"},
			{Name: "--status"},
			{Name: "--search"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"Creates a local `.mbr-knowledge/checkout.json` manifest so later pull, push, and status flows can reason about the working copy safely.",
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "status"},
		Usage:        "mbr knowledge status [PATH] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Compare a local knowledge working copy against the current server state.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "PATH"}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"Reports whether the working copy is clean, ahead, behind, diverged, or has local-only/server-only files.",
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "pull"},
		Usage:        "mbr knowledge pull [PATH] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Apply server changes into a checked-out local knowledge working copy.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "PATH"}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"Pull refuses to overwrite tracked local changes; resolve them first or push them before pulling.",
			"Local-only files outside the tracked checkout manifest are preserved.",
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "push"},
		Usage:        "mbr knowledge push [PATH] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Push tracked local knowledge edits back to the server and refresh the checkout manifest.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "PATH"}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"Push applies tracked updates, tracked deletions, and local-only files created inside the checkout root.",
			"Push still refuses to run when the working copy is behind or diverged from the current server state.",
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "delete"},
		Usage:        "mbr knowledge delete RESOURCE [--workspace WORKSPACE_ID --team TEAM_ID --surface SURFACE] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Delete a knowledge resource and remove its git-backed artifact.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "RESOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "sync"},
		Usage:        "mbr knowledge sync PATH [--workspace WORKSPACE_ID] [--team TEAM_ID] [--surface SURFACE] [--kind KIND] [--concept-spec KEY] [--concept-version VERSION] [--status STATUS] [--review-status STATUS] [--share-with TEAM_IDS] [--source-kind KIND] [--source-ref REF] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Sync Markdown files into team-owned Git-backed knowledge resources.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "PATH", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--kind"},
			{Name: "--concept-spec"},
			{Name: "--concept-version"},
			{Name: "--status"},
			{Name: "--review-status"},
			{Name: "--share-with"},
			{Name: "--source-kind"},
			{Name: "--source-ref"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "import"},
		Usage:        "mbr knowledge import PATH [--workspace WORKSPACE_ID] [--team TEAM_ID] [--surface SURFACE] [--kind KIND] [--concept-spec KEY] [--concept-version VERSION] [--status STATUS] [--review-status STATUS] [--share-with TEAM_IDS] [--source-kind KIND] [--source-ref REF] [--mode preview|apply] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Preview or apply a team-oriented Markdown knowledge import.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "PATH", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--kind"},
			{Name: "--concept-spec"},
			{Name: "--concept-version"},
			{Name: "--status"},
			{Name: "--review-status"},
			{Name: "--share-with"},
			{Name: "--source-kind"},
			{Name: "--source-ref"},
			{Name: "--mode"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "review"},
		Usage:        "mbr knowledge review RESOURCE [--workspace WORKSPACE_ID --team TEAM_ID --surface SURFACE] [--status STATUS] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Mark a knowledge resource as reviewed or approved.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "RESOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--status"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "publish"},
		Usage:        "mbr knowledge publish RESOURCE [--workspace WORKSPACE_ID --team TEAM_ID --surface SURFACE] [--to-surface SURFACE] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Publish a knowledge resource onto a non-private surface.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "RESOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--to-surface"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "share"},
		Usage:        "mbr knowledge share RESOURCE [--workspace WORKSPACE_ID --team TEAM_ID --surface SURFACE] --share-with TEAM_IDS [--url URL] [--token TOKEN] [--json]",
		Summary:      "Share a knowledge resource with additional teams.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "RESOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--share-with", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "history"},
		Usage:        "mbr knowledge history RESOURCE [--workspace WORKSPACE_ID --team TEAM_ID --surface SURFACE] [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show Git-backed revision history for a knowledge resource.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "RESOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "knowledge",
		Path:         []string{"knowledge", "diff"},
		Usage:        "mbr knowledge diff RESOURCE [--workspace WORKSPACE_ID --team TEAM_ID --surface SURFACE] [--from REVISION] [--to REVISION] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a Git patch for a knowledge resource.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "RESOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--surface"},
			{Name: "--from"},
			{Name: "--to"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "concepts",
		Path:         []string{"concepts", "list"},
		Usage:        "mbr concepts list [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List built-in and workspace concept specs.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "concepts",
		Path:         []string{"concepts", "show"},
		Usage:        "mbr concepts show KEY [--workspace WORKSPACE_ID] [--version VERSION] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a concept spec definition.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "KEY", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--version"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "concepts",
		Path:         []string{"concepts", "register"},
		Usage:        "mbr concepts register FILE [--workspace WORKSPACE_ID] [--team TEAM_ID] [--source-kind KIND] [--source-ref REF] [--status STATUS] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Register a versioned concept spec from a YAML definition file.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "FILE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--team"},
			{Name: "--source-kind"},
			{Name: "--source-ref"},
			{Name: "--status"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "concepts",
		Path:         []string{"concepts", "history"},
		Usage:        "mbr concepts history KEY [--workspace WORKSPACE_ID] [--version VERSION] [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show Git-backed revision history for a concept spec.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "KEY", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--version"},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "concepts",
		Path:         []string{"concepts", "diff"},
		Usage:        "mbr concepts diff KEY [--workspace WORKSPACE_ID] [--version VERSION] [--from REVISION] [--to REVISION] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a Git patch for a concept spec definition.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "KEY", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--version"},
			{Name: "--from"},
			{Name: "--to"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "artifacts",
		Path:         []string{"artifacts", "list"},
		Usage:        "mbr artifacts list --extension EXTENSION_ID --surface SURFACE [--url URL] [--token TOKEN] [--json]",
		Summary:      "List managed files on an extension artifact surface.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--extension", Required: true},
			{Name: "--surface", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "artifacts",
		Path:         []string{"artifacts", "show"},
		Usage:        "mbr artifacts show --extension EXTENSION_ID --surface SURFACE --path PATH [--ref REVISION] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show the current or historical content of a managed extension artifact.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--extension", Required: true},
			{Name: "--surface", Required: true},
			{Name: "--path", Required: true},
			{Name: "--ref"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "artifacts",
		Path:         []string{"artifacts", "history"},
		Usage:        "mbr artifacts history --extension EXTENSION_ID --surface SURFACE --path PATH [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show revision history for a managed extension artifact.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--extension", Required: true},
			{Name: "--surface", Required: true},
			{Name: "--path", Required: true},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "artifacts",
		Path:         []string{"artifacts", "diff"},
		Usage:        "mbr artifacts diff --extension EXTENSION_ID --surface SURFACE --path PATH [--from REVISION] [--to REVISION] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a Git patch for a managed extension artifact.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--extension", Required: true},
			{Name: "--surface", Required: true},
			{Name: "--path", Required: true},
			{Name: "--from"},
			{Name: "--to"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "artifacts",
		Path:         []string{"artifacts", "publish"},
		Usage:        "mbr artifacts publish --extension EXTENSION_ID --surface SURFACE --path PATH (--file FILE | --content TEXT) [--url URL] [--token TOKEN] [--json]",
		Summary:      "Publish new content onto a managed extension artifact surface.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--extension", Required: true},
			{Name: "--surface", Required: true},
			{Name: "--path", Required: true},
			{Name: "--file"},
			{Name: "--content"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "queues",
		Path:         []string{"queues", "list"},
		Usage:        "mbr queues list [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List queues in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "queues",
		Path:         []string{"queues", "show"},
		Usage:        "mbr queues show QUEUE_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a queue.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "QUEUE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "queues",
		Path:         []string{"queues", "create"},
		Usage:        "mbr queues create [--workspace WORKSPACE_ID] --name NAME [--slug SLUG] [--description TEXT] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a queue.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--name", Required: true},
			{Name: "--slug"},
			{Name: "--description"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "queues",
		Path:         []string{"queues", "items"},
		Usage:        "mbr queues items QUEUE_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "List the concrete work items currently visible in a queue.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals: []PositionalSpec{
			{Name: "queue_id", Required: true},
		},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"Returns `queue_item` records with linked case or conversation summaries.",
		},
	},
	{
		Section:      "conversations",
		Path:         []string{"conversations", "list"},
		Usage:        "mbr conversations list [--workspace WORKSPACE_ID] [--status STATUS] [--channel CHANNEL] [--catalog-node NODE_ID] [--contact CONTACT_ID] [--case CASE_ID] [--limit N] [--offset N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List conversations in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--status"},
			{Name: "--channel"},
			{Name: "--catalog-node"},
			{Name: "--contact"},
			{Name: "--case"},
			{Name: "--limit"},
			{Name: "--offset"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "conversations",
		Path:         []string{"conversations", "show"},
		Usage:        "mbr conversations show SESSION_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a conversation with messages and working state.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "SESSION_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "conversations",
		Path:         []string{"conversations", "reply"},
		Usage:        "mbr conversations reply SESSION_ID [--participant PARTICIPANT_ID] [--role ROLE] [--kind KIND] [--visibility VISIBILITY] (--content TEXT | --file PATH) [--url URL] [--token TOKEN] [--json]",
		Summary:      "Append a message to a conversation.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "SESSION_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--participant"},
			{Name: "--role"},
			{Name: "--kind"},
			{Name: "--visibility"},
			{Name: "--content"},
			{Name: "--file"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "conversations",
		Path:         []string{"conversations", "handoff"},
		Usage:        "mbr conversations handoff SESSION_ID --queue QUEUE_ID [--team TEAM_ID] [--operator USER_ID] [--reason TEXT] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Hand off a conversation to a queue and optionally a target team or operator.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "SESSION_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--queue", Required: true},
			{Name: "--team"},
			{Name: "--operator"},
			{Name: "--reason"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"Use this when an agent needs to route a live conversation to another team or operator on behalf of its human.",
		},
	},
	{
		Section:      "conversations",
		Path:         []string{"conversations", "escalate"},
		Usage:        "mbr conversations escalate SESSION_ID --queue QUEUE_ID [--team TEAM_ID] [--operator USER_ID] [--subject TEXT] [--description TEXT] [--priority PRIORITY] [--category TEXT] [--reason TEXT] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a case from a conversation and place the resulting work in a queue.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "SESSION_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--queue", Required: true},
			{Name: "--team"},
			{Name: "--operator"},
			{Name: "--subject"},
			{Name: "--description"},
			{Name: "--priority"},
			{Name: "--category"},
			{Name: "--reason"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
		Notes: []string{
			"The created case keeps the originating conversation ID so case work stays tied to its source thread.",
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "list"},
		Usage:        "mbr forms list [--workspace WORKSPACE_ID] [--status STATUS] [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List forms in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--status"},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "forms",
		Path:         []string{"forms", "create"},
		Usage:        "mbr forms create [--workspace WORKSPACE_ID] --name NAME --slug SLUG [--description TEXT] [--definition-file PATH | --definition-json JSON] [--status STATUS] [--public] [--requires-captcha] [--collect-email] [--auto-create-case] [--submission-message TEXT] [--redirect-url URL] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a form.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--name", Required: true},
			{Name: "--slug", Required: true},
			{Name: "--description"},
			{Name: "--definition-file"},
			{Name: "--definition-json"},
			{Name: "--status"},
			{Name: "--public"},
			{Name: "--requires-captcha"},
			{Name: "--collect-email"},
			{Name: "--auto-create-case"},
			{Name: "--submission-message"},
			{Name: "--redirect-url"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "automation",
		Path:         []string{"automation", "rules", "list"},
		Usage:        "mbr automation rules list [--workspace WORKSPACE_ID] [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List automation rules in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "automation",
		Path:         []string{"automation", "rules", "create"},
		Usage:        "mbr automation rules create [--workspace WORKSPACE_ID] --title TITLE (--conditions-file PATH | --conditions-json JSON) (--actions-file PATH | --actions-json JSON) [--description TEXT] [--active] [--priority N] [--max-per-hour N] [--max-per-day N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create an automation rule.",
		SupportsJSON: true,
		AuthMode:     AuthModeSessionOnly,
		AuthNote:     "Requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--title", Required: true},
			{Name: "--conditions-file"},
			{Name: "--conditions-json"},
			{Name: "--actions-file"},
			{Name: "--actions-json"},
			{Name: "--description"},
			{Name: "--active"},
			{Name: "--priority"},
			{Name: "--max-per-hour"},
			{Name: "--max-per-day"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "create"},
		Usage:        "mbr cases create [--workspace WORKSPACE_ID] --subject TEXT [--description TEXT] [--priority PRIORITY] [--category TEXT] [--queue QUEUE_ID] [--contact-id CONTACT_ID] [--contact-email EMAIL] [--contact-name NAME] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Create a case in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--subject", Required: true},
			{Name: "--description"},
			{Name: "--priority"},
			{Name: "--category"},
			{Name: "--queue"},
			{Name: "--contact-id"},
			{Name: "--contact-email"},
			{Name: "--contact-name"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "list"},
		Usage:        "mbr cases list [--workspace WORKSPACE_ID] [--status STATUS] [--priority PRIORITY] [--queue QUEUE_ID] [--assignee USER_ID] [--limit N] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List cases in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--status"},
			{Name: "--priority"},
			{Name: "--queue"},
			{Name: "--assignee"},
			{Name: "--limit"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "show"},
		Usage:        "mbr cases show CASE_ID [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show a single case.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Positionals:  []PositionalSpec{{Name: "CASE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "assign"},
		Usage:        "mbr cases assign CASE_ID --assignee USER_ID [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Assign a case to a user.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "CASE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--assignee", Required: true},
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "unassign"},
		Usage:        "mbr cases unassign CASE_ID [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Remove the assignee from a case.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "CASE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "set-priority"},
		Usage:        "mbr cases set-priority CASE_ID --priority PRIORITY [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Update case priority.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "CASE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--priority", Required: true},
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "set-status"},
		Usage:        "mbr cases set-status CASE_ID --status STATUS [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Update case status.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "CASE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--status", Required: true},
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "handoff"},
		Usage:        "mbr cases handoff CASE_ID --queue QUEUE_ID [--team TEAM_ID] [--assignee USER_ID] [--reason TEXT] [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Move a case between teams and queues while preserving case-thread audit history.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "CASE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--queue", Required: true},
			{Name: "--team"},
			{Name: "--assignee"},
			{Name: "--reason"},
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "add-note"},
		Usage:        "mbr cases add-note CASE_ID --body TEXT [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Add an internal note to a case.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "CASE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--body", Required: true},
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "cases",
		Path:         []string{"cases", "reply"},
		Usage:        "mbr cases reply CASE_ID --body TEXT [--subject TEXT] [--to EMAILS] [--cc EMAILS] [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Send a case reply to the case contact or explicit recipients.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "CASE_ID", Required: true}},
		Flags: []FlagSpec{
			{Name: "--body", Required: true},
			{Name: "--subject"},
			{Name: "--to"},
			{Name: "--cc"},
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "contacts",
		Path:         []string{"contacts", "list"},
		Usage:        "mbr contacts list [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List contacts in a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "attachments",
		Path:         []string{"attachments", "upload"},
		Usage:        "mbr attachments upload PATH [--workspace WORKSPACE_ID] [--case CASE_ID] [--description TEXT] [--content-type MIME] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Upload an attachment to a workspace or case.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "PATH", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--case"},
			{Name: "--description"},
			{Name: "--content-type"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "health",
		Path:         []string{"health", "check"},
		Usage:        "mbr health check [--url URL] [--token TOKEN] [--json]",
		Summary:      "Check instance health.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "fleet",
		Path:         []string{"fleet", "register"},
		Usage:        "mbr fleet register [--config PATH] [--fleet-url URL] [--instance-id ID] [--instance-name NAME] [--operator-email ADDRESS] [--use-case internal_ops|startup|client_deployment|personal|other] [--registration-source self_hosted|managed] [--platform-version VERSION] [--tracking-secret SECRET | --tracking-secret-file PATH] [--tracking-secret-out PATH] [--json]",
		Summary:      "Register or update one instance in the Move Big Rocks fleet control plane.",
		SupportsJSON: true,
		AuthMode:     AuthModeNone,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--config"},
			{Name: "--fleet-url"},
			{Name: "--instance-id"},
			{Name: "--instance-name"},
			{Name: "--operator-email"},
			{Name: "--use-case"},
			{Name: "--registration-source"},
			{Name: "--platform-version"},
			{Name: "--tracking-secret"},
			{Name: "--tracking-secret-file"},
			{Name: "--tracking-secret-out"},
			{Name: "--json"},
		},
		Notes: []string{
			"Registration is explicit and does not make the core runtime depend on vendor availability.",
			"When the fleet control plane issues a new tracking secret, `--tracking-secret-out` writes it to a local file so host automation can store it securely.",
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "list"},
		Usage:        "mbr extensions list ([--workspace WORKSPACE_ID] | --instance) [--url URL] [--token TOKEN] [--json]",
		Summary:      "List installed extensions.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--instance"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "lint"},
		Usage:        "mbr extensions lint SOURCE_DIR [--contract PATH] [--write-contract] [--json]",
		Summary:      "Validate an extension source tree and compare it with its contract file.",
		SupportsJSON: true,
		AuthMode:     AuthModeNone,
		Operation:    OperationLocal,
		Idempotency:  IdempotencyLocalState,
		Positionals:  []PositionalSpec{{Name: "SOURCE_DIR", Required: true}},
		Flags: []FlagSpec{
			{Name: "--contract"},
			{Name: "--write-contract"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "verify"},
		Usage:        "mbr extensions verify SOURCE_DIR [--workspace WORKSPACE_ID] [--license-token TOKEN] [--contract PATH] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Install an extension from source and prove its contract, navigation, widgets, seeded resources, validation, and health.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		AuthNote:     "Provisioning a dedicated workspace during verify requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "SOURCE_DIR", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--license-token"},
			{Name: "--contract"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "nav"},
		Usage:        "mbr extensions nav ([--workspace WORKSPACE_ID] | --instance) [--url URL] [--token TOKEN] [--json]",
		Summary:      "List resolved extension admin navigation items.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--instance"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "widgets"},
		Usage:        "mbr extensions widgets ([--workspace WORKSPACE_ID] | --instance) [--url URL] [--token TOKEN] [--json]",
		Summary:      "List resolved extension dashboard widgets.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--instance"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "show"},
		Usage:        "mbr extensions show --id EXTENSION_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show extension details.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "deploy"},
		Usage:        "mbr extensions deploy BUNDLE_SOURCE [--workspace WORKSPACE_ID] [--license-token TOKEN] [--config-file PATH | --config-json JSON] [--no-activate] [--no-monitor] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Deploy an extension into a preview or target workspace by composing install or upgrade, validate, activate, and monitor.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		AuthNote:     "Provisioning a dedicated workspace during deploy requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "BUNDLE_SOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--license-token"},
			{Name: "--config-file"},
			{Name: "--config-json"},
			{Name: "--no-activate"},
			{Name: "--no-monitor"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "monitor"},
		Usage:        "mbr extensions monitor --id EXTENSION_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Refresh and show extension runtime health.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions-events",
		Path:         []string{"extensions", "events", "list"},
		Usage:        "mbr extensions events list [--workspace WORKSPACE_ID] [--url URL] [--token TOKEN] [--json]",
		Summary:      "List runtime event catalog entries for a workspace.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions-skills",
		Path:         []string{"extensions", "skills", "list"},
		Usage:        "mbr extensions skills list --id EXTENSION_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "List bundled agent skills for an extension.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions-skills",
		Path:         []string{"extensions", "skills", "show"},
		Usage:        "mbr extensions skills show --id EXTENSION_ID --name SKILL_NAME [--url URL] [--token TOKEN] [--json]",
		Summary:      "Show bundled skill content for an extension.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationRead,
		Idempotency:  IdempotencyReadOnly,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--name", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "install"},
		Usage:        "mbr extensions install BUNDLE_SOURCE [--workspace WORKSPACE_ID] [--license-token TOKEN] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Install an extension from a bundle file, directory, HTTPS URL, OCI ref, or marketplace alias.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		AuthNote:     "Provisioning a dedicated workspace during install requires browser login or MBR_SESSION_TOKEN.",
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "BUNDLE_SOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--workspace"},
			{Name: "--license-token"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "upgrade"},
		Usage:        "mbr extensions upgrade BUNDLE_SOURCE --id EXTENSION_ID [--license-token TOKEN] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Upgrade an installed extension.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Positionals:  []PositionalSpec{{Name: "BUNDLE_SOURCE", Required: true}},
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--license-token"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "configure"},
		Usage:        "mbr extensions configure --id EXTENSION_ID (--config-file PATH | --config-json JSON) [--url URL] [--token TOKEN] [--json]",
		Summary:      "Update extension configuration.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--config-file"},
			{Name: "--config-json"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "validate"},
		Usage:        "mbr extensions validate --id EXTENSION_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Validate an installed extension.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "activate"},
		Usage:        "mbr extensions activate --id EXTENSION_ID [--url URL] [--token TOKEN] [--json]",
		Summary:      "Activate an installed extension.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "deactivate"},
		Usage:        "mbr extensions deactivate --id EXTENSION_ID [--reason TEXT] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Deactivate an installed extension.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--reason"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
	{
		Section:      "extensions",
		Path:         []string{"extensions", "uninstall"},
		Usage:        "mbr extensions uninstall --id EXTENSION_ID [--deactivate] [--reason TEXT] [--export-out PATH | --confirm-no-export] [--dry-run] [--url URL] [--token TOKEN] [--json]",
		Summary:      "Plan and uninstall an extension, optionally deactivating and exporting state first.",
		SupportsJSON: true,
		AuthMode:     AuthModeBearerOrSession,
		Operation:    OperationWrite,
		Idempotency:  IdempotencyServerManaged,
		Flags: []FlagSpec{
			{Name: "--id", Required: true},
			{Name: "--deactivate"},
			{Name: "--reason"},
			{Name: "--export-out"},
			{Name: "--confirm-no-export"},
			{Name: "--dry-run"},
			{Name: "--url"},
			{Name: "--token"},
			{Name: "--json"},
		},
	},
}

var authModes = []AuthModeSpec{
	{
		Name:        AuthModeNone,
		Label:       "No remote auth required",
		Description: "The command does not require an authenticated Move Big Rocks session or token.",
	},
	{
		Name:        AuthModeLocal,
		Label:       "Local CLI state",
		Description: "The command only reads or mutates local CLI configuration.",
	},
	{
		Name:        AuthModeBearerOrSession,
		Label:       "Bearer token or browser-backed session",
		Description: "The command accepts either a workspace-scoped bearer token or a stored/session-backed CLI login.",
	},
	{
		Name:        AuthModeSessionOnly,
		Label:       "Browser-backed session only",
		Description: "The command requires browser login or MBR_SESSION_TOKEN.",
	},
}

var extensionInstallSources = []string{
	"bundle_file",
	"directory",
	"https_url",
	"oci_ref",
	"marketplace_alias",
}

func Sections() []SectionSpec {
	return append([]SectionSpec(nil), sections...)
}

func Commands() []CommandSpec {
	return append([]CommandSpec(nil), commands...)
}

func CommandsForSection(section string) []CommandSpec {
	var filtered []CommandSpec
	for _, command := range commands {
		if command.Section == section {
			filtered = append(filtered, command)
		}
	}
	return filtered
}

func Section(section string) (SectionSpec, bool) {
	for _, candidate := range sections {
		if candidate.Key == section {
			return candidate, true
		}
	}
	return SectionSpec{}, false
}

func CurrentSpec() Spec {
	return Spec{
		SchemaVersion:           "mbr-cli-contract-v1",
		PrimarySurface:          "cli_first",
		CanonicalMachineAPI:     "graphql",
		CommandRegistrySource:   "internal/clispec",
		ExtensionInstallSources: append([]string(nil), extensionInstallSources...),
		AuthModes:               append([]AuthModeSpec(nil), authModes...),
		Sections:                Sections(),
		Commands:                Commands(),
	}
}

func AuthModeLabel(mode AuthMode) string {
	for _, candidate := range authModes {
		if candidate.Name == mode {
			return candidate.Label
		}
	}
	return string(mode)
}
