CREATE TABLE ${SCHEMA_NAME}.identity_providers (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    extension_install_id UUID NOT NULL,
    public_id TEXT NOT NULL DEFAULT '',
    provider_type TEXT NOT NULL DEFAULT 'oidc',
    display_name TEXT NOT NULL DEFAULT '',
    issuer TEXT NOT NULL DEFAULT '',
    discovery_url TEXT NOT NULL DEFAULT '',
    authorization_url TEXT NOT NULL DEFAULT '',
    token_url TEXT NOT NULL DEFAULT '',
    user_info_url TEXT NOT NULL DEFAULT '',
    jwks_url TEXT NOT NULL DEFAULT '',
    client_id TEXT NOT NULL DEFAULT '',
    client_secret_ref TEXT NOT NULL DEFAULT '',
    redirect_url TEXT NOT NULL DEFAULT '',
    scopes JSONB NOT NULL DEFAULT '[]',
    claim_mapping JSONB NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'draft',
    enforce_sso BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
