CREATE TABLE ${SCHEMA_NAME}.events (
    id BIGSERIAL PRIMARY KEY,
    workspace_id UUID NOT NULL,
    extension_install_id UUID NOT NULL,
    property_id UUID NOT NULL REFERENCES ${SCHEMA_NAME}.properties(id),
    visitor_id BIGINT NOT NULL DEFAULT 0,
    name TEXT NOT NULL DEFAULT 'pageview',
    pathname TEXT NOT NULL DEFAULT '',
    referrer_source TEXT NOT NULL DEFAULT '',
    utm_source TEXT NOT NULL DEFAULT '',
    utm_medium TEXT NOT NULL DEFAULT '',
    utm_campaign TEXT NOT NULL DEFAULT '',
    country_code TEXT NOT NULL DEFAULT '',
    region TEXT NOT NULL DEFAULT '',
    city TEXT NOT NULL DEFAULT '',
    browser TEXT NOT NULL DEFAULT '',
    os TEXT NOT NULL DEFAULT '',
    device_type TEXT NOT NULL DEFAULT '',
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ${SCHEMA_NAME}.sessions (
    session_id BIGSERIAL PRIMARY KEY,
    workspace_id UUID NOT NULL,
    extension_install_id UUID NOT NULL,
    property_id UUID NOT NULL REFERENCES ${SCHEMA_NAME}.properties(id),
    visitor_id BIGINT NOT NULL DEFAULT 0,
    entry_page TEXT NOT NULL DEFAULT '',
    exit_page TEXT NOT NULL DEFAULT '',
    referrer_source TEXT NOT NULL DEFAULT '',
    utm_source TEXT NOT NULL DEFAULT '',
    utm_medium TEXT NOT NULL DEFAULT '',
    utm_campaign TEXT NOT NULL DEFAULT '',
    country_code TEXT NOT NULL DEFAULT '',
    region TEXT NOT NULL DEFAULT '',
    city TEXT NOT NULL DEFAULT '',
    browser TEXT NOT NULL DEFAULT '',
    os TEXT NOT NULL DEFAULT '',
    device_type TEXT NOT NULL DEFAULT '',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_activity TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    duration INTEGER NOT NULL DEFAULT 0,
    pageviews INTEGER NOT NULL DEFAULT 0,
    is_bounce BOOLEAN NOT NULL DEFAULT true
);
