package platformservices

import internalplatformservices "github.com/movebigrocks/platform/internal/platform/services"

type ContactService = internalplatformservices.ContactService
type CreateContactParams = internalplatformservices.CreateContactParams
type ExtensionService = internalplatformservices.ExtensionService
type WorkspaceManagementService = internalplatformservices.WorkspaceManagementService
type UserManagementService = internalplatformservices.UserManagementService
type ResolvedExtensionAdminNavigationItem = internalplatformservices.ResolvedExtensionAdminNavigationItem
type ResolvedExtensionDashboardWidget = internalplatformservices.ResolvedExtensionDashboardWidget

var NewContactService = internalplatformservices.NewContactService
var NewExtensionService = internalplatformservices.NewExtensionService
